#!/bin/bash
if [ ! "$(docker ps -q -f name="foo")" ]; then
    if [ "$(docker ps -aq -f status=exited -f name="foo")" ]; then
echo "Данного докера не существует, производим создание";
docker build -t foo .

docker run -it foo
fi
fi
